spring.application.name=temple-billing
spring.datasource.url=jdbc:mysql://localhost:3306/temple_billing
spring.datasource.username=root
spring.datasource.password=root@123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true
jwt.secret=MankurussiBhagavathiTempleApiSecretKey
jwt.expiration=86400000
server.port=${PORT:8080}

spring.profiles.active=prod

# MYSQLDUMP PATH (IMPORTANT)
#C:\\Program Files\\MySQL\\MySQL Server 8.0\\bin\\mysqldump.exe
backup.mysql.mac.path=/usr/local/mysql-9.1.0-macos14-arm64/bin/mysqldump
backup.mysql.windows.path=C:/Program Files/MySQL/MySQL Server 8.0/bin/mysqldump.exe

# GOOGLE DRIVE BACKUP PATH
backup.output.dir.windows=C:/Users/YourUser/Google Drive/DB_BACKUPS/
backup.output.dir.mac=/Users/abhilashc/Documents/Works/backup/

backup.file.prefix=temple_backup_
# KEEP ONLY LAST N FILES
backup.retain.count=3