# PostgreSQL Configuration
spring.datasource.url=postgresql://templeuser:W7CBmJBF2mtvHMpKtim6TrrHBlMf9XtF@dpg-d6ru0c75gffc73892tj0-a.oregon-postgres.render.com/templedb_8j9u
spring.datasource.username=templeuser
spring.datasource.password=W7CBmJBF2mtvHMpKtim6TrrHBlMf9XtF
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# JPA Hibernate Configuration (Optional)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true